language: node_js
node_js:
  - "8"

notifications:
  email: false

install:
  - npm install -g codecov istanbul
  - npm install

script:
  - npm run lint
  - npm test
  - istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec test/**/*.js
  - codecov
